# Generated by Django 5.0.4 on 2024-05-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_issue', '0003_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logissue',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
        migrations.AlterField(
            model_name='logissue',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
    ]
