# Generated by Django 5.0.4 on 2024-05-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_issue', '0005_alter_logissue_latitude_alter_logissue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logissue',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
